### ISSUE TITLE
DO WE HAVE LATEST GDB BUILD GUILDE

### ISSUE THREAD

**Issue by hezhiye** [jhswartz/static-builds#1]
Hi:
   thanks for your sharing, do we have latest gdb static build guide like gdb version 11.2 ? thanks

**Comment by jhswartz** [comment]
Thanks for your interest in this project.

After reading your message, I spent some time building gdb v11.2. The process is basically the same as before for gdb v9.1, although the existing patch lines (sed commands) have changed to account for the "gdbserver" directory having moved out of "gdb".

You will also notice an extra patch line, that adjusts the number of maintenance workers spawned during gdb initialisation from "unlimited" (or -1) to 0. This is necessary if your target doesn't play nicely with std::thread for whatever reason.

Let me know how it goes.

**Comment by hezhiye** [comment]
Hi jhswartz:
    Thanks for your relay. I meet below issue when i check your lastest build guide.

checking size of unsigned long...   CXXLD  gdbreplay
ld: error: undefined symbol: tdesc_architecture_name(target_desc const*)
>>> referenced by tdesc.cc:408 (../../gdbsupport/tdesc.cc:408)
>>>               tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
>>> referenced by tdesc.cc:409 (../../gdbsupport/tdesc.cc:409)
>>>               tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a

ld: error: undefined symbol: tdesc_osabi_name(target_desc const*)
>>> referenced by tdesc.cc:412 (../../gdbsupport/tdesc.cc:412)
>>>               tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a

ld: error: undefined symbol: tdesc_compatible_info_list(target_desc const*)
>>> referenced by tdesc.cc:417 (../../gdbsupport/tdesc.cc:417)
>>>               tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a

ld: error: undefined symbol: tdesc_compatible_info_arch_name(std::unique_ptr<tdesc_compatible_info, std::default_delete<tdesc_compatible_info> > const&)
>>> referenced by tdesc.cc:419 (../../gdbsupport/tdesc.cc:419)
>>>               tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:377: gdbreplay] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by hezhiye** [comment]
Hi jhswartz:
    
after fallback the step 2-3 to old one (yes, it will fail in patch but will be ok in build)and use step 4,  the gdb can be successfully build. 
Patch：
1.$ sed -i -e 's/$MISSING makeinfo/true/g' configure
2.$ sed -i -e "s/RDYNAMIC=['\"].*['\"]/RDYNAMIC=''/g" gdb/{,gdbserver/}configure
3.$ sed -i -e 's/^CC_LD.*$/& -static/g' gdb/{,gdbserver/}Makefile.in
# If you receive SIGABRT immediately after executing gdb:
4.$ sed -i -e 's/n_worker_threads = -1/n_worker_threads = 0/g' gdb/maint.c

Although the step 2-3 fail in gdbserver as you said that the "gdbserver" directory having moved out of "gdb",   the gdb ld: error will disappear.  I do not know the root cause,  anyway,  the gdb works well. thanks very much for your help.

**Comment by jhswartz** [comment]
Regarding:

> checking size of unsigned long... CXXLD gdbreplay ld: error: undefined symbol: tdesc_architecture_name(target_desc const*)
> 
> > > > referenced by tdesc.cc:408 (../../gdbsupport/tdesc.cc:408)
> > > > tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
> > > > referenced by tdesc.cc:409 (../../gdbsupport/tdesc.cc:409)
> > > > tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
> 
> ld: error: undefined symbol: tdesc_osabi_name(target_desc const*)
> 
> > > > referenced by tdesc.cc:412 (../../gdbsupport/tdesc.cc:412)
> > > > tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
> 
> ld: error: undefined symbol: tdesc_compatible_info_list(target_desc const*)
> 
> > > > referenced by tdesc.cc:417 (../../gdbsupport/tdesc.cc:417)
> > > > tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
> 
> ld: error: undefined symbol: tdesc_compatible_info_arch_name(std::unique_ptr<tdesc_compatible_info, std::default_delete<tdesc_compatible_info> > const&)
> 
> > > > referenced by tdesc.cc:419 (../../gdbsupport/tdesc.cc:419)
> > > > tdesc.o:(print_xml_feature::visit_pre(target_desc const*)) in archive ../gdbsupport/libgdbsupport.a
> > > > collect2: error: ld returned 1 exit status
> > > > make[2]: *** [Makefile:377: gdbreplay] Error 1
> > > > make[2]: *** Waiting for unfinished jobs....

Are you building with expat? I didn't have it installed, so gdb didn't use it - and I didn't have these errors.


> after fallback the step 2-3 to old one (yes, it will fail in patch but will be ok in build)and use step 4, the gdb can be successfully build.
> Patch：
> 1.$ sed -i -e 's/$MISSING makeinfo/true/g' configure
> 2.$ sed -i -e "s/RDYNAMIC=['"].['"]/RDYNAMIC=''/g" gdb/{,gdbserver/}configure
> 3.$ sed -i -e 's/^CC_LD.$/& -static/g' gdb/{,gdbserver/}Makefile.in

These should be necessary to ensure static objects are generated without dymanic linkage, have you checked the resultant binaries to ensure they are static? You can use the file command built with your target toolchain, or poke inside the ELF headers.

**Comment by hezhiye** [comment]
HI jhswartz:
     yes, i have checked my env is using expat like below, also i have checked the result is static  like below:

configure:9499: checking whether to use expat
configure:9501: result: auto
configure:9934: checking for libexpat
configure:9953: x86_64-linux-gnu-gcc -o conftest -g -O2        conftest.c -ltermcap -lm -ldl  -lexpat >&5
configure:9953: $? = 0
configure:9963: result: yes
configure:9970: checking how to link with libexpat
configure:9972: result: -lexpat
configure:9998: checking for XML_StopParser
configure:9998: x86_64-linux-gnu-gcc -o conftest -g -O2        conftest.c -ltermcap -lm -ldl  -lexpat >&5
configure:9998: $? = 0
configure:9998: result: yes


file gdb
gdb: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[xxHash]=3110cea6e6241713, with debug_info, not stripped

thanks very much

**Comment by hezhiye** [comment]
My configure of project is : ../configure --host="${TARGET}" --prefix="${STATIC_ROOT}" --disable-sim  --disable-gdbserver --disable-tui --with-python=no  and it works
